import { test, expect } from './fixtures.mjs'
import { experiments } from '../../src/data/aiExperiments.js'

for (const language of ['es','en','ca']) test(`all AI experiments share layout and language ${language}`, async ({ page }) => {
  await page.addInitScript(value => localStorage.setItem('portfolio-language',value),language)
  for (const experiment of experiments) {
    await page.goto(`/ai/${experiment.id}`)
    await expect(page.locator('main h1')).toHaveText(experiment.title[language])
    await expect(page.locator('.ai-tabs a[aria-current="page"]')).toHaveAttribute('href',`/ai/${experiment.id}`)
    await expect(page.locator('.ai-tabs a')).toHaveCount(6)
    await expect(page.locator('.ai-tabs a[aria-current="page"]')).toBeInViewport()
    await expect(page.locator('.ai-method')).toContainText(experiment.method[language])
    expect(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  }
  await page.locator('.ai-back').click();await expect(page).toHaveURL(/\/ai$/)
  await expect(page.locator('.ai-featured')).toHaveAttribute('href','/ai/neural-network')
  await expect(page.locator('.ai-catalog-item')).toHaveCount(5)
})

test('neural model loads locally, gives real probabilities and clears without a prediction', async ({ page }) => {
  await page.goto('/ai/neural-network')
  await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  await page.locator('.ai-samples').getByRole('button',{name:'7',exact:true}).click()
  await expect(page.getByTestId('predicted-digit')).toBeVisible()
  const probabilities=await page.locator('[data-probability]').evaluateAll(elements => elements.map(e=>Number(e.dataset.probability)))
  expect(probabilities).toHaveLength(10);expect(probabilities.every(v=>Number.isFinite(v)&&v>=0&&v<=1)).toBe(true)
  expect(probabilities.reduce((a,b)=>a+b,0)).toBeCloseTo(1,8)
  expect(await page.locator('.ai-network-diagram circle').count()).toBe(986)
  await page.getByRole('button',{name:'Limpiar',exact:true}).click()
  await expect(page.getByTestId('predicted-digit')).toHaveCount(0)
  await expect(page).toHaveURL(/\/ai\/neural-network$/)
})

test('neural load failure never returns random predictions and retry recovers', async ({ page }) => {
  let fail=true
  await page.route('**/models/mnist/*.json',route => fail ? route.fulfill({status:503,body:'Unavailable'}) : route.continue())
  await page.goto('/ai/neural-network')
  await expect(page.getByTestId('model-state')).toContainText('No se pudo cargar')
  await page.locator('.ai-samples').getByRole('button',{name:'1',exact:true}).click()
  await expect(page.getByTestId('predicted-digit')).toHaveCount(0)
  fail=false;await page.getByRole('button',{name:'Reintentar',exact:true}).click()
  await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  await expect(page.getByTestId('predicted-digit')).toBeVisible()
})

test('scaled drawing canvas accepts mouse and touch and erases', async ({ page },testInfo) => {
  await page.goto('/ai/neural-network')
  await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  const canvas=page.locator('.ai-drawing-canvas')
  await canvas.evaluate(element => { element.style.width='140px' })
  await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox()
  if(testInfo.project.name==='mobile') await page.touchscreen.tap(box.x+70,box.y+70)
  else { await page.mouse.move(box.x+70,box.y+30);await page.mouse.down();await page.mouse.move(box.x+70,box.y+100,{steps:6});await page.mouse.up() }
  await expect(page.getByTestId('predicted-digit')).toBeVisible()
  const center=await canvas.evaluate(element => {const ctx=element.getContext('2d');return ctx.getImageData(140,140,1,1).data[0]})
  expect(center).toBeGreaterThan(0)
  await page.getByRole('button',{name:'Limpiar',exact:true}).click()
  await expect(page.getByTestId('predicted-digit')).toHaveCount(0)
})

test('network view works by keyboard and returns to its initial angle', async ({ page }) => {
  await page.goto('/ai/neural-network')
  const angle=page.getByLabel('Ángulo de la vista')
  await angle.focus();await page.keyboard.press('ArrowRight');await expect(angle).toHaveValue('29')
  await page.getByRole('button',{name:'Restablecer vista',exact:true}).click();await expect(angle).toHaveValue('28')
})

test('Tetris pause freezes gravity and AI, and resume keeps the same game', async ({ page }) => {
  await page.goto('/ai/tetris')
  const board=page.getByTestId('tetris-board')
  await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
  await page.getByRole('button',{name:'Pausar',exact:true}).click()
  const position=await board.getAttribute('data-position')
  await page.waitForTimeout(1200)
  await expect(board).toHaveAttribute('data-position',position)
  await expect(page.getByRole('button',{name:'Que la IA decida',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'Continuar',exact:true}).first().click()
  await board.focus();await page.keyboard.press('ArrowLeft')
  await expect(board).not.toHaveAttribute('data-position',position)
})

test('Tetris keyboard drop, AI placement and restart use valid settled pieces', async ({ page }) => {
  await page.goto('/ai/tetris')
  const board=page.getByTestId('tetris-board')
  await board.focus();await page.keyboard.press(' ')
  await expect(board).toHaveAttribute('data-score','10')
  expect(await board.locator('[data-settled]:not([data-settled=""])').count()).toBeGreaterThanOrEqual(4)
  await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
  await page.getByRole('button',{name:'Que la IA decida',exact:true}).click()
  await expect(board).toHaveAttribute('data-score',/^(20|120|220|320|420)$/)
  await page.getByRole('button',{name:'Nueva partida',exact:true}).click()
  await expect(board).toHaveAttribute('data-score','0')
  await expect(board.locator('[data-settled]:not([data-settled=""])')).toHaveCount(0)
  await expect(page.locator('[data-preview-filled="true"]')).toHaveCount(await page.locator('.ai-tetris-preview').getAttribute('aria-label').then(label=>label.endsWith(': T')?5:4))
})

test('Tetris game shortcuts do not hijack header or toolbar keyboard actions', async ({ page }) => {
  await page.goto('/ai/tetris')
  await page.getByRole('button',{name:'Pausar',exact:true}).click()
  const board=page.getByTestId('tetris-board'),position=await board.getAttribute('data-position')
  const music=page.getByRole('button',{name:'Música',exact:true})
  await music.focus();await page.keyboard.press(' ')
  await expect(board).toHaveAttribute('data-position',position)
  await expect(board).toHaveAttribute('data-paused','true')
})

test('tic-tac-toe locks the opponent turn and reset cancels its old reply', async ({ page }) => {
  await page.goto('/ai/tictactoe')
  const cells=page.locator('.ai-cell')
  await cells.first().click()
  await expect(cells.nth(1)).toBeDisabled()
  await page.getByRole('button',{name:'Nuevo Juego',exact:true}).click()
  await page.waitForTimeout(700)
  expect((await cells.allTextContents()).join('').trim()).toBe('')
})

test('Minesweeper flag mode works by touch and removes the flag', async ({ page }) => {
  await page.goto('/ai/minesweeper')
  await page.getByRole('button',{name:'Marcar banderas',exact:true}).click()
  const cell=page.locator('.ai-mines-board .ai-cell').first()
  await cell.click();await expect(cell).toContainText('🚩')
  await cell.click();await expect(cell).not.toContainText('🚩')
})

test('Nim reset cancels a pending opponent move', async ({ page }) => {
  await page.goto('/ai/nim')
  await page.getByRole('button',{name:'Retirar 1 · Montón 1',exact:true}).click()
  await page.getByRole('button',{name:'Nuevo Juego',exact:true}).click()
  await page.waitForTimeout(1200)
  await expect(page.locator('.ai-nim-piles > div > div')).toHaveText(['1','3','5','7'])
})

test('Six Degrees exposes examples, trims input, reports errors and finds a sample path', async ({ page }) => {
  await page.goto('/ai/sixdegrees')
  await page.getByRole('button',{name:'Kevin Bacon → Tom Hanks',exact:true}).click()
  await page.locator('#graph-source').fill(' Kevin Bacon ')
  await page.getByRole('button',{name:'Encontrar Camino',exact:true}).click()
  await expect(page.getByText('¡Encontrado!',{exact:false})).toBeVisible()
  await page.locator('#graph-source').fill('Unknown QA name')
  await page.getByRole('button',{name:'Encontrar Camino',exact:true}).click()
  await expect(page.getByText('No está en el conjunto de muestra: Unknown QA name',{exact:true})).toBeVisible()
})

test('old neural URL leads to the integrated visualization', async ({ page }) => {
  await page.goto('/neural-network.html')
  await expect(page).toHaveURL(/\/ai\/neural-network$/)
  await expect(page.locator('main h1')).toHaveText('Red neuronal')
})

test('Nim trains the expert locally and re-enables play when complete', async ({ page }) => {
  await page.goto('/ai/nim')
  await expect(page.locator('.ai-help').first()).toContainText('pierde')
  await page.getByRole('button',{name:'IA Experta (10,000 juegos)',exact:true}).click()
  await expect(page.locator('.ai-pile-move').first()).toBeDisabled()
  await expect(page.locator('.ai-pile-move').first()).toBeEnabled({timeout:15000})
})

test('Six Degrees uses verified film edges to find a multi-step path', async ({ page }) => {
  await page.goto('/ai/sixdegrees')
  await page.locator('#graph-source').fill('Tom Cruise');await page.locator('#graph-target').fill('Helen Hunt')
  await page.getByRole('button',{name:'Encontrar Camino',exact:true}).click()
  await expect(page.getByText('¡Encontrado! 3 grados de separación.',{exact:true})).toBeVisible()
  await expect(page.locator('.ai-stage a[href="https://www.sonypictures.com/movies/afewgoodmen"]')).toBeVisible()
  await expect(page.locator('.ai-stage a[href="https://amblin.com/movie/cast-away/"]')).toBeVisible()
})

test('desktop Tetris accepts keys without an initial click and AI works with previews off', async ({page},testInfo) => {
  test.skip(testInfo.project.name==='mobile','Desktop physical-keyboard journey')
  await page.goto('/ai/tetris')
  const board=page.getByTestId('tetris-board'),before=await board.getAttribute('data-position')
  await page.keyboard.press('ArrowLeft')
  await expect(board).not.toHaveAttribute('data-position',before)
  await expect(page.getByRole('button',{name:'IA desactivada',exact:true})).toBeVisible()
  await page.keyboard.press('a');await expect(board).toHaveAttribute('data-score',/^(10|110|210|310|410)$/)
  await page.getByRole('button',{name:'Nueva partida',exact:true}).click()
  await page.getByRole('button',{name:'Que la IA decida',exact:true}).click()
  await expect(board).toHaveAttribute('data-score',/^(10|110|210|310|410)$/)
  const afterAI=await board.getAttribute('data-position');await page.keyboard.press('ArrowRight')
  await expect(board).not.toHaveAttribute('data-position',afterAI)
})
test('Tetris keeps AI preview outside the live board and every active piece inside its walls',async({page})=>{
  await page.goto('/ai/tetris')
  await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
  await expect(page.getByTestId('tetris-ai-plan')).toBeVisible()
  const board=page.getByTestId('tetris-board')
  await expect(board.locator('.is-suggestion')).toHaveCount(0)
  for(let i=0;i<12;i++){
    await page.getByRole('button',{name:'Que la IA decida',exact:true}).click()
    const positions=await board.locator('[data-active]:not([data-active=""])').evaluateAll(es=>es.map(e=>e.dataset.active.split(',').map(Number)))
    expect(positions.every(([r,c])=>r>=0&&r<20&&c>=0&&c<10)).toBe(true)
    if(positions.length)expect(Math.max(...positions.map(([,c])=>c))-Math.min(...positions.map(([,c])=>c))).toBeLessThanOrEqual(3)
  }
})
test('all ten neural examples draw distinct non-empty inputs and produce real probabilities',async({page})=>{
  await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  await expect(page.getByText('Prueba un ejemplo',{exact:true})).toHaveCount(1)
  await expect(page.locator('.ai-samples')).toHaveCount(1)
  await expect(page.locator('.ai-samples button')).toHaveCount(10)
  const inputs=[]
  for(let digit=0;digit<10;digit++){
    await page.locator('.ai-samples').getByRole('button',{name:String(digit),exact:true}).click()
    await expect(page.getByTestId('predicted-digit')).toBeVisible()
    await expect(page.locator('.ai-samples').getByRole('button',{name:String(digit),exact:true})).toHaveAttribute('aria-pressed','true')
    await expect(page.getByTestId('predicted-digit')).toHaveText(String(digit))
    const pixels=await page.locator('.ai-drawing-canvas').evaluate(canvas=>Array.from(canvas.getContext('2d').getImageData(0,0,280,280).data).filter((_,i)=>i%4===0))
    expect(pixels.some(value=>value>0)).toBe(true);inputs.push(pixels.join(','))
    const probabilities=await page.locator('[data-probability]').evaluateAll(es=>es.map(e=>Number(e.dataset.probability)))
    expect(probabilities.reduce((a,b)=>a+b,0)).toBeCloseTo(1,8)
  }
  expect(new Set(inputs).size).toBe(10)
})
test('neural layer tracing and inspection expose the actual signal and camera reset',async({page})=>{
  await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  await page.locator('.ai-samples').getByRole('button',{name:'4',exact:true}).click()
  await page.getByRole('button',{name:'Recorrer las capas',exact:false}).click()
  await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-active-layer','0')
  await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-active-layer','3',{timeout:6000})
  await page.getByText('Inspeccionar una neurona',{exact:true}).click()
  const neuron=page.getByLabel('Neurona',{exact:true});await neuron.focus();await page.keyboard.press('ArrowRight')
  await expect(page.locator('.ai-node-inspector output')).toContainText('Activación:')
  await page.getByRole('button',{name:'Restablecer vista',exact:true}).click()
  await expect(page.getByLabel('Ángulo de la vista')).toHaveValue('28')
  await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-active-layer','3')
  await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-animation-paused','true')
  await page.getByRole('button',{name:'Todas las etapas',exact:false}).click()
  await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-active-layer','all')
})
test('Magic T visibly dissolves after contact and pause freezes its sand frames',async({page})=>{
  await page.addInitScript(()=>{Math.random=()=>0.95})
  await page.goto('/ai/tetris')
  const board=page.getByTestId('tetris-board')
  await expect(board).toHaveAttribute('data-piece-name','T')
  await page.keyboard.press(' ')
  await expect(board).toHaveAttribute('data-settling','true')
  await expect(board).toHaveAttribute('data-score','0')
  await expect(page.getByRole('button',{name:'Que la IA decida',exact:true})).toBeDisabled()
  await page.keyboard.press('p')
  const frame=await board.getAttribute('data-settle-frame')
  await page.waitForTimeout(450)
  await expect(board).toHaveAttribute('data-settle-frame',frame)
  await expect(board).toHaveAttribute('data-settling','true')
  await page.keyboard.press('p')
  await expect(board.locator('.ai-magic-voxel.is-flowing')).not.toHaveCount(0)
  await expect(board).toHaveAttribute('data-settling','false',{timeout:6000})
  await expect(board).toHaveAttribute('data-score','10')
  await expect(board.locator('[data-settled="T"]')).toHaveCount(5)
  await expect(page.getByRole('button',{name:'Que la IA decida',exact:true})).toBeEnabled()
})
test.describe('completed-line flash',()=>{
  test.use({reducedMotion:'no-preference'})
  test('two completed rows flash before removal and pause freezes completion',async({page})=>{
    await page.addInitScript(()=>{Math.random=()=>0.66})
    await page.goto('/ai/tetris')
    const board=page.getByTestId('tetris-board')
    await expect(board).toHaveAttribute('data-piece-name','O')
    for(const [index,column]of [0,2,4,6].entries()){
      await board.focus()
      for(let step=0;step<Math.abs(column-4);step++)await page.keyboard.press(column<4?'ArrowLeft':'ArrowRight')
      await page.keyboard.press(' ');await expect(board).toHaveAttribute('data-score',String((index+1)*10))
    }
    await board.focus();for(let step=0;step<4;step++)await page.keyboard.press('ArrowRight')
    await page.keyboard.press(' ');await page.keyboard.press('p')
    await expect(board).toHaveAttribute('data-clearing','true')
    await expect(board).toHaveAttribute('data-clear-rows','18,19')
    await expect(board.locator('.is-clearing')).toHaveCount(20)
    await expect(board).toHaveAttribute('data-score','40')
    const style=await board.locator('.is-clearing').first().evaluate(e=>({name:getComputedStyle(e,'::after').animationName,play:getComputedStyle(e,'::after').animationPlayState}))
    expect(style.name).toBe('line-clear-blink');expect(style.play).toBe('paused')
    await page.waitForTimeout(450);await expect(board).toHaveAttribute('data-clearing','true')
    await page.keyboard.press('p');await expect(board).toHaveAttribute('data-clearing','false')
    await expect(board).toHaveAttribute('data-score','250')
    await expect(board.locator('[data-settled]:not([data-settled=""])')).toHaveCount(0)
    await expect(page.locator('.ai-tetris-stats div').filter({has:page.getByText('Líneas',{exact:true})}).locator('dd')).toHaveText('2')
  })
})
test('ten neural OUTPUT neurons form one 3D column and inference edges show actual contributions',async({page})=>{
  await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  const buttons=page.locator('.ai-samples button');await expect(buttons).toHaveCount(10)
  const sampleRows=await buttons.evaluateAll(es=>es.map(e=>Math.round(e.getBoundingClientRect().top)));expect(new Set(sampleRows).size).toBe(2)
  const outputs=page.locator('circle[data-layer="3"]');await expect(outputs).toHaveCount(10)
  const row=await outputs.evaluateAll(es=>es.map(e=>({x:e.cx.baseVal.value,y:e.cy.baseVal.value,index:Number(e.dataset.nodeIndex)})))
  expect(new Set(row.map(node=>node.x)).size).toBe(1)
  expect(row.map(node=>node.index)).toEqual([0,1,2,3,4,5,6,7,8,9])
  expect(row.every((node,index)=>index===0||node.y>row[index-1].y)).toBe(true)
  await expect(page.locator('[data-output-label]')).toHaveCount(10)
  await page.getByLabel('Ángulo de la vista',{exact:true}).focus();await page.keyboard.press('Home')
  const rotated=await outputs.evaluateAll(es=>es.map(e=>({x:e.cx.baseVal.value,y:e.cy.baseVal.value})))
  expect(new Set(rotated.map(node=>node.x)).size).toBe(1)
  expect(rotated[0].x).not.toBe(row[0].x)
  const finalEdges=await page.locator('line[data-edge-layer="2"]').evaluateAll(es=>es.map(e=>({target:Number(e.dataset.target),x:e.x2.baseVal.value,y:e.y2.baseVal.value})))
  expect(finalEdges.every(edge=>edge.x===rotated[edge.target].x&&edge.y===rotated[edge.target].y)).toBe(true)
  await page.getByRole('button',{name:'Restablecer vista',exact:true}).click()
  await page.getByRole('button',{name:'Recorrer las capas',exact:false}).click()
  await expect(page.getByTestId('neural-trace-panel')).toHaveAttribute('data-trace-phase','input')
  await page.getByRole('button',{name:'Paso siguiente',exact:true}).click()
  await expect(page.getByTestId('neural-trace-panel')).toHaveAttribute('data-trace-phase','f1')
  await expect(page.locator('.neural-flow-edge')).not.toHaveCount(0)
  const edge=await page.locator('line[data-edge-layer="0"]').first().evaluate(e=>({source:Number(e.dataset.source),target:Number(e.dataset.target),weight:Number(e.dataset.weight),contribution:Number(e.dataset.contribution)}))
  const actual=await page.locator('.ai-drawing-canvas').evaluate(async(canvas,edge)=>{
    const data=await fetch('/models/mnist/014_dataset-1x.json').then(r=>r.json()),tensor=data.layers[0].weights
    const b=Uint8Array.from(atob(tensor.data),c=>c.charCodeAt(0)),view=new DataView(b.buffer),h=view.getUint16((edge.target*784+edge.source)*2,true),exp=(h>>10)&31,frac=h&1023,sign=h&0x8000?-1:1
    const weight=exp===0?sign*2**-14*frac/1024:sign*2**(exp-15)*(1+frac/1024)
    const c=document.createElement('canvas');c.width=c.height=28;const ctx=c.getContext('2d');ctx.drawImage(canvas,0,0,28,28);const pixel=ctx.getImageData(0,0,28,28).data[edge.source*4]/255
    return {weight,contribution:weight*((pixel-0.1307)/0.3081)}
  },edge)
  expect(edge.weight).toBe(actual.weight);expect(edge.contribution).toBeCloseTo(actual.contribution,10)
  await page.getByLabel('Zoom',{exact:true}).focus();await page.keyboard.press('End')
  await expect(page.getByLabel('Zoom',{exact:true})).toHaveValue('1.2')
  const outputIsVisible=()=>page.locator('.ai-network-instrument svg').evaluate(svg=>{
    const bounds=svg.getBoundingClientRect()
    return [...svg.querySelectorAll('circle[data-layer="3"],[data-output-label]')].every(node=>{const box=node.getBoundingClientRect();return box.left>=bounds.left&&box.right<=bounds.right&&box.top>=bounds.top&&box.bottom<=bounds.bottom})
  })
  expect(await outputIsVisible()).toBe(true)
  await page.getByLabel('Ángulo de la vista',{exact:true}).focus();await page.keyboard.press('Home')
  for(let step=0;step<60;step++)await page.keyboard.press('ArrowRight')
  await expect(page.getByLabel('Ángulo de la vista',{exact:true})).toHaveValue('0')
  expect(await outputIsVisible()).toBe(true)
})
test('neural single picker keeps the drawn input distinct from its real sensitivity',async({page})=>{
  await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
  await expect(page.locator('.neural-studio select')).toHaveCount(0)
  await expect(page.getByText('Número correcto',{exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Ver un paso de entrenamiento',exact:true})).toHaveCount(0)
  const sample=page.locator('.ai-samples').getByRole('button',{name:'3',exact:true})
  await sample.click();await expect(sample).toHaveAttribute('aria-pressed','true')
  const probabilities=()=>page.locator('[data-probability]').evaluateAll(es=>es.map(e=>Number(e.dataset.probability)))
  const original=await probabilities(),input=page.locator('circle[data-layer="0"]')
  const values=()=>input.evaluateAll(es=>es.map(e=>Number(e.dataset.nodeValue)))
  const pixels=await values()
  await page.getByRole('button',{name:'Backpropagation',exact:false}).click()
  await page.getByRole('button',{name:'01 / Entrada',exact:false}).click()
  await expect(input.first()).toHaveAttribute('data-value-kind','gradient')
  await page.getByText('Inspeccionar una neurona',{exact:true}).click()
  const sensitivity=page.getByLabel('Mostrar sensibilidad de los píxeles',{exact:true})
  await expect(sensitivity).toBeChecked()
  const gradients=await values()
  expect(gradients.some((value,index)=>value!==pixels[index])).toBe(true)
  expect(await input.evaluateAll(es=>es.every(e=>e.dataset.nodeValue===e.dataset.inputGradient))).toBe(true)
  await sensitivity.uncheck();expect(await values()).toEqual(pixels)
  expect(await probabilities()).toEqual(original)
  await page.getByRole('button',{name:'Limpiar',exact:true}).click()
  await expect(sample).toHaveAttribute('aria-pressed','true')
  await expect(page.getByTestId('predicted-digit')).toHaveCount(0)
  const canvas=page.locator('.ai-drawing-canvas')
  await canvas.evaluate(element=>element.scrollIntoView({block:'center',behavior:'instant'}))
  const box=await canvas.boundingBox()
  await page.mouse.move(box.x+box.width*0.25,box.y+box.height*0.25);await page.mouse.down()
  await page.mouse.move(box.x+box.width*0.75,box.y+box.height*0.3,{steps:6})
  await page.mouse.move(box.x+box.width*0.55,box.y+box.height*0.55,{steps:6})
  await page.mouse.move(box.x+box.width*0.75,box.y+box.height*0.75,{steps:6});await page.mouse.up()
  await expect(page.getByTestId('predicted-digit')).toBeVisible()
  await expect(sample).toHaveAttribute('aria-pressed','true')
  const p=await probabilities(),deltas=await page.locator('circle[data-layer="3"]').evaluateAll(es=>es.map(e=>Number(e.dataset.nodeValue)))
  deltas.forEach((value,index)=>expect(value).toBeCloseTo(p[index]-(index===3?1:0),12))
  await sample.click();expect(await probabilities()).toEqual(original)
})
test.describe('independent neural inspection controls',()=>{
  test.use({reducedMotion:'no-preference'})
  test('all stages and each direction preserve pause/on-off, real gradients and the base model',async({page})=>{
    await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
    const instrument=page.locator('.ai-network-instrument'),panel=page.getByTestId('neural-trace-panel')
    const original=await page.locator('[data-probability]').evaluateAll(es=>es.map(e=>Number(e.dataset.probability)))
    const flowLayers=()=>page.locator('.neural-flow-edge').evaluateAll(es=>[...new Set(es.map(e=>Number(e.dataset.flowLayer)))].sort())
    await expect(panel).toHaveAttribute('data-trace-phase','allForward');expect(await flowLayers()).toEqual([0,1,2])
    await page.getByRole('button',{name:'Pausar animación',exact:true}).click()
    await page.getByRole('button',{name:'02 / Capa oculta 1',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','f1');expect(await flowLayers()).toEqual([0])
    await page.getByRole('button',{name:'Backpropagation',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','b1');expect(await flowLayers()).toEqual([1])
    await expect(instrument).toHaveAttribute('data-animation-enabled','true')
    await expect(instrument).toHaveAttribute('data-animation-paused','true')
    await expect(instrument).toHaveAttribute('data-flow-playing','false')
    const line=page.locator('.neural-flow-edge').first()
    const offset=await line.evaluate(e=>getComputedStyle(e).strokeDashoffset)
    await page.waitForTimeout(200);expect(await line.evaluate(e=>getComputedStyle(e).strokeDashoffset)).toBe(offset)
    await page.getByRole('button',{name:'04 / Salida',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','outputGradient')
    const deltas=await page.locator('circle[data-layer="3"]').evaluateAll(es=>es.map(e=>Number(e.dataset.nodeValue)))
    deltas.forEach((value,index)=>expect(value).toBeCloseTo(original[index]-(index===7?1:0),12))
    await page.locator('.ai-samples').getByRole('button',{name:'3',exact:true}).click()
    const labelledProbabilities=await page.locator('[data-probability]').evaluateAll(es=>es.map(e=>Number(e.dataset.probability)))
    const relabelled=await page.locator('circle[data-layer="3"]').evaluateAll(es=>es.map(e=>Number(e.dataset.nodeValue)))
    relabelled.forEach((value,index)=>expect(value).toBeCloseTo(labelledProbabilities[index]-(index===3?1:0),12))
    await page.locator('.ai-samples').getByRole('button',{name:'7',exact:true}).click()
    await page.getByRole('switch',{name:'Apagar animación',exact:true}).click()
    await expect(page.getByRole('button',{name:'Continuar animación',exact:true})).toBeDisabled()
    await page.getByRole('button',{name:'01 / Entrada',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','b0');await expect(page.locator('.neural-flow-edge')).toHaveCount(0)
    await page.getByRole('button',{name:'Todas las etapas',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','allBackward')
    await expect(instrument).toHaveAttribute('data-animation-enabled','false')
    await page.getByRole('switch',{name:'Encender animación',exact:true}).click()
    await expect(instrument).toHaveAttribute('data-flow-playing','false');expect(await flowLayers()).toEqual([0,1,2])
    await page.getByRole('button',{name:'Continuar animación',exact:true}).click()
    await expect(instrument).toHaveAttribute('data-flow-playing','true')
    const edge=await page.locator('line[data-edge-layer="2"]').first().evaluate(e=>({weight:Number(e.dataset.weight),target:Number(e.dataset.target),signal:Number(e.dataset.signal)}))
    expect(edge.signal).toBeCloseTo(edge.weight*deltas[edge.target],12)
    await page.getByRole('button',{name:'Hacia delante',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','allForward')
    expect(await page.locator('[data-probability]').evaluateAll(es=>es.map(e=>Number(e.dataset.probability)))).toEqual(original)
    await page.getByRole('switch',{name:'Apagar animación',exact:true}).click()
    await page.getByRole('button',{name:'Backpropagation',exact:false}).click()
    await page.getByRole('button',{name:'03 / Capa oculta 2',exact:false}).click()
    await page.locator('.ai-samples').getByRole('button',{name:'8',exact:true}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','b2')
    await expect(instrument).toHaveAttribute('data-animation-enabled','false')
    await expect(instrument).toHaveAttribute('data-animation-paused','false')
    await expect(page.getByTestId('predicted-digit')).toHaveText('8')
    await expect(page.locator('.neural-flow-edge')).toHaveCount(0)
  })
  test('direct stage selection cancels an inference walkthrough without restarting motion',async({page})=>{
    await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
    await page.getByRole('button',{name:'Recorrer las capas',exact:false}).click()
    await page.getByRole('button',{name:'Pausar animación',exact:true}).click()
    for(let i=0;i<2;i++)await page.getByRole('button',{name:'Paso siguiente',exact:true}).click()
    await page.getByRole('button',{name:'01 / Entrada',exact:false}).click()
    await page.getByRole('button',{name:'Backpropagation',exact:false}).click()
    const panel=page.getByTestId('neural-trace-panel'),instrument=page.locator('.ai-network-instrument')
    await expect(panel).toHaveAttribute('data-trace-mode','inspection')
    await expect(panel).toHaveAttribute('data-trace-phase','b0')
    await expect(instrument).toHaveAttribute('data-animation-paused','true')
    await page.waitForTimeout(1600)
    await expect(panel).toHaveAttribute('data-trace-phase','b0')
    await page.getByRole('button',{name:'Hacia delante',exact:false}).click()
    await expect(panel).toHaveAttribute('data-trace-phase','input')
    await expect(page.locator('.neural-flow-node')).not.toHaveCount(0)
    await expect(page.locator('.neural-flow-node').first()).toHaveCSS('animation-play-state','paused')
    await page.getByRole('switch',{name:'Apagar animación',exact:true}).click()
    await expect(page.locator('.neural-flow-node')).toHaveCount(0)
  })
})

test.describe('complete input gradient transport',()=>{
  test.use({reducedMotion:'no-preference'})
  test('each returning bundle equals the full128-source derivative and lands on its cell',async({page})=>{
    await page.goto('/ai/neural-network');await expect(page.getByTestId('model-state')).toContainText('Modelo cargado')
    await page.getByRole('button',{name:'Backpropagation',exact:false}).click()
    await page.getByRole('button',{name:'01 / Entrada',exact:false}).click()
    const routes=page.locator('[data-input-route]'),cells=page.locator('[data-input-cell]')
    await expect(routes).toHaveCount(784);await expect(cells).toHaveCount(784)
    await expect(page.getByTestId('input-gradient-transport')).toHaveAttribute('data-source-count','128')
    const accuracy=await page.evaluate(async()=>{
      const data=await fetch('/models/mnist/014_dataset-1x.json').then(r=>r.json()),tensor=data.layers[0].weights
      const bytes=Uint8Array.from(atob(tensor.data),c=>c.charCodeAt(0)),view=new DataView(bytes.buffer)
      const deltas=[...document.querySelectorAll('circle[data-layer="1"]')].map(e=>Number(e.dataset.nodeValue))
      const pixels=[...document.querySelectorAll('circle[data-layer="0"]')],cells=[...document.querySelectorAll('[data-input-cell]')],routes=[...document.querySelectorAll('[data-input-route]')]
      let maxError=0
      const coherent=routes.every(route=>{
        const i=Number(route.dataset.inputRoute);let sum=0
        for(let j=0;j<128;j++){
          const half=view.getUint16((j*784+i)*2,true),sign=half&0x8000?-1:1,exp=half>>10&31,frac=half&1023
          const weight=exp===0?sign*2**-14*frac/1024:sign*2**(exp-15)*(1+frac/1024)
          sum+=weight*deltas[j]
        }
        sum/=data.normalization?.std??0.3081
        maxError=Math.max(maxError,Math.abs(sum-Number(route.dataset.signal)))
        const pixel=pixels[i],cell=cells[i],endpoint=route.getPointAtLength(0)
        return route.dataset.signal===cell.dataset.gradient&&route.dataset.signal===pixel.dataset.inputGradient&&endpoint.x===pixel.cx.baseVal.value&&endpoint.y===pixel.cy.baseVal.value&&getComputedStyle(route).stroke===getComputedStyle(cell).fill
      })
      return {maxError,coherent}
    })
    expect(accuracy.maxError).toBeLessThan(1e-10);expect(accuracy.coherent).toBe(true)
    await expect(page.getByTestId('input-gradient-pulses')).toHaveCSS('animation-name','neural-input-return')
    await expect(page.getByTestId('input-gradient-cells')).toHaveCSS('animation-name','neural-input-arrival')
    await page.getByRole('button',{name:'Pausar animación',exact:true}).click()
    const offset=await page.getByTestId('input-gradient-pulses').evaluate(e=>getComputedStyle(e).strokeDashoffset)
    await page.waitForTimeout(220)
    expect(await page.getByTestId('input-gradient-pulses').evaluate(e=>getComputedStyle(e).strokeDashoffset)).toBe(offset)
    await page.getByRole('switch',{name:'Apagar animación',exact:true}).click()
    await expect(page.getByTestId('input-gradient-pulses')).toHaveCount(0)
    await expect(cells).toHaveCount(784)
    await cells.nth(100).click()
    await expect(page.locator('.ai-node-inspector output')).toContainText('Gradiente:')
    await expect(page.locator('.ai-network-instrument')).toHaveAttribute('data-animation-paused','true')
  })
})
