import { test, expect } from './fixtures.mjs'
import { tetrisSpecials } from '../../src/data/tetrisSpecials.js'
import { labCopy } from '../../src/data/aiExperiments.js'

const moveTo = async (page, column) => {
  const board=page.getByTestId('tetris-board'), current=Number((await board.getAttribute('data-position')).split(',')[1])
  await board.focus()
  for(let i=0;i<Math.abs(column-current);i++)await page.keyboard.press(column<current?'ArrowLeft':'ArrowRight')
}
const mini = locator => locator.locator('[data-cell-kind]').evaluateAll(cells=>cells.map(cell=>cell.dataset.cellKind))
const settled = board => board.locator('[data-settled]').evaluateAll(cells=>cells.map(cell=>cell.dataset.settled))

for(const language of ['es','en','ca'])test(`special rules and practice starts are translated in ${language}`,async({page})=>{
  await page.addInitScript(language=>localStorage.setItem('portfolio-language',language),language)
  await page.goto('/ai/tetris')
  const copy={...labCopy[language],...tetrisSpecials[language]}
  await expect(page.locator('.ai-tetris-plan-board')).toHaveCount(0)
  await page.locator('.ai-tetris-specials summary').click()
  await expect(page.locator('.ai-tetris-specials')).toContainText(copy.crystalHint)
  await expect(page.locator('.ai-tetris-specials')).toContainText(copy.drillHint)
  await page.getByRole('button',{name:copy.startCrystal,exact:true}).click()
  const board=page.getByTestId('tetris-board')
  await expect(board).toHaveAttribute('data-piece-name','C');await expect(board.locator('[data-active]:not([data-active=""])')).toHaveCount(4)
  await expect(board.locator('[data-active]:not([data-active=""])[data-crystal-life="3"]')).toHaveCount(4)
  await page.getByRole('button',{name:copy.aiOff,exact:true}).click()
  await expect(page.getByTestId('tetris-drop-plan')).toBeVisible();await expect(page.getByTestId('tetris-ai-plan')).toBeVisible()
  await expect(page.locator('.ai-tetris-plan-board:visible')).toHaveCount(2)
  await page.getByRole('button',{name:copy.startDrill,exact:true}).click()
  await expect(board).toHaveAttribute('data-piece-name','D');await expect(board.locator('[data-active]:not([data-active=""])')).toHaveCount(3)
  await expect(page.locator('.ai-tetris-preview')).toHaveCount(2)
  await page.getByRole('button',{name:copy.aiOn,exact:true}).click()
  await expect(page.locator('.ai-tetris-plan-board')).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test.describe('new special reactions',()=>{
  test.use({reducedMotion:'no-preference'})
  test('Crystal ghost equals settlement, lives three placements and pause freezes its visible break',async({page})=>{
    await page.addInitScript(()=>{Math.random=()=>0.8})
    await page.goto('/ai/tetris');await page.locator('.ai-tetris-specials summary').click()
    await page.getByRole('button',{name:'Empezar con Cristal',exact:true}).click()
    await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
    const board=page.getByTestId('tetris-board')
    const expected=await mini(page.getByTestId('tetris-drop-plan'))
    await board.focus();await page.keyboard.press(' ')
    await expect(board).toHaveAttribute('data-turn','1')
    expect(await settled(board)).toEqual(expected)
    await expect(board.locator('[data-settled="C"][data-crystal-life="3"]')).toHaveCount(4)
    await moveTo(page,8);await page.keyboard.press(' ')
    await expect(board).toHaveAttribute('data-turn','2')
    await expect(board.locator('[data-settled="C"][data-crystal-life="2"]')).toHaveCount(4)
    await moveTo(page,0)
    await expect(board.locator('.will-expire')).toHaveCount(0)
    await page.keyboard.press(' ');await expect(board).toHaveAttribute('data-turn','3')
    await expect(board.locator('[data-settled="C"][data-crystal-life="1"]')).toHaveCount(4)
    await moveTo(page,1)
    const afterExpiry=await mini(page.getByTestId('tetris-drop-plan'))
    const queue=page.locator('.ai-tetris-queue'),queueTop=await queue.evaluate(e=>e.getBoundingClientRect().top+scrollY)
    await expect(board.locator('.will-expire')).toHaveCount(4)
    await page.keyboard.press(' ');await page.keyboard.press('p')
    await expect(board).toHaveAttribute('data-cracking','true');await expect(board).toHaveAttribute('data-paused','true')
    await expect(page.getByTestId('tetris-drop-plan')).toBeVisible()
    expect(await queue.evaluate(e=>e.getBoundingClientRect().top+scrollY)).toBeCloseTo(queueTop,3)
    await expect(board.locator('.is-breaking')).toHaveCount(4)
    await expect(board.locator('.is-breaking').first()).toHaveCSS('animation-name','crystal-break')
    await expect(board.locator('.is-breaking').first()).toHaveCSS('animation-play-state','paused')
    await page.waitForTimeout(500);await expect(board).toHaveAttribute('data-turn','3');await expect(board).toHaveAttribute('data-score','30')
    await page.keyboard.press('p');await expect(board).toHaveAttribute('data-turn','4')
    expect(await queue.evaluate(e=>e.getBoundingClientRect().top+scrollY)).toBeCloseTo(queueTop,3)
    await expect(board.locator('[data-settled="C"]')).toHaveCount(0)
    expect(await settled(board)).toEqual(afterExpiry)
  })
  test('Drill marks exactly what it will remove and advances down real frames with pause',async({page})=>{
    await page.addInitScript(()=>{Math.random=()=>0.86})
    await page.goto('/ai/tetris');await page.locator('.ai-tetris-specials summary').click()
    await page.getByRole('button',{name:'Empezar con Taladro',exact:true}).click()
    await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
    const board=page.getByTestId('tetris-board')
    await board.focus();await page.keyboard.press(' ');await expect(board).toHaveAttribute('data-turn','1')
    await expect(board.locator('[data-settled="D"]')).toHaveCount(3)
    await expect(board.locator('[data-will-drill="true"]')).toHaveCount(2)
    const expected=await mini(page.getByTestId('tetris-drop-plan'))
    await page.keyboard.press(' ');await page.keyboard.press('p')
    await expect(board).toHaveAttribute('data-drilling','true')
    const position=await board.getAttribute('data-position'),frame=await board.getAttribute('data-drill-frame')
    await page.waitForTimeout(350)
    await expect(board).toHaveAttribute('data-position',position);await expect(board).toHaveAttribute('data-drill-frame',frame)
    await expect(board.locator('.ai-drill-voxel').first()).toHaveCSS('animation-play-state','paused')
    await page.keyboard.press('p');await expect(board).toHaveAttribute('data-turn','2')
    expect(await settled(board)).toEqual(expected)
    await expect(board.locator('[data-settled="D"]')).toHaveCount(4)
    await expect(board).toHaveAttribute('data-score','20')
  })
})

test('horizontal Drill stops against three supports and its forecast matches the board',async({page})=>{
  await page.addInitScript(()=>{Math.random=()=>0.86})
  await page.goto('/ai/tetris')
  await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
  const board=page.getByTestId('tetris-board')
  for(const[index,column]of[3,4,5].entries()){
    await moveTo(page,column);await page.keyboard.press(' ');await expect(board).toHaveAttribute('data-turn',String(index+1))
  }
  await board.focus();await page.keyboard.press('ArrowUp')
  await expect(board.locator('[data-will-drill="true"]')).toHaveCount(0)
  const expected=await mini(page.getByTestId('tetris-drop-plan'))
  await page.keyboard.press(' ');await expect(board).toHaveAttribute('data-turn','4')
  expect(await settled(board)).toEqual(expected)
  await expect(board.locator('[data-settled="D"]')).toHaveCount(12)
})

test('AI shows its real two-piece Crystal continuation and reset rejects old reaction timers',async({page})=>{
  await page.addInitScript(()=>{Math.random=()=>0.8})
  await page.goto('/ai/tetris');await page.locator('.ai-tetris-specials summary').click()
  await page.getByRole('button',{name:'Empezar con Cristal',exact:true}).click()
  await page.getByRole('button',{name:'IA desactivada',exact:true}).click()
  await expect(page.locator('[data-forecast-steps]')).toHaveAttribute('data-forecast-steps','2')
  await page.locator('.ai-tetris-forecast summary').click()
  await expect(page.getByTestId('tetris-ai-forecast')).toBeVisible()
  const forecast=await mini(page.getByTestId('tetris-ai-forecast'))
  expect(forecast.filter(name=>name==='C').length).toBeGreaterThan(0)
  await expect(page.getByTestId('tetris-ai-forecast').locator('[data-cell-kind="C"][data-life="1"]')).toHaveCount(forecast.filter(name=>name==='C').length)
  const plan=await mini(page.getByTestId('tetris-ai-plan'))
  await page.getByRole('button',{name:'Que la IA decida',exact:true}).click()
  const board=page.getByTestId('tetris-board');await expect(board).toHaveAttribute('data-turn','1')
  expect(await settled(board)).toEqual(plan)
  await page.getByRole('button',{name:'Empezar con Taladro',exact:true}).click()
  await board.focus();await page.keyboard.press(' ')
  await page.getByRole('button',{name:'Nueva partida',exact:true}).click()
  await page.waitForTimeout(500)
  await expect(board).toHaveAttribute('data-score','0');await expect(board).toHaveAttribute('data-turn','0')
  await expect(board).toHaveAttribute('data-drilling','false');await expect(board).toHaveAttribute('data-cracking','false')
})

test('specials disclosure keyboard works without dropping a piece',async({page})=>{
  await page.goto('/ai/tetris');await page.getByRole('button',{name:'Pausar',exact:true}).click()
  const summary=page.locator('.ai-tetris-specials summary')
  await summary.focus();await page.keyboard.press(' ')
  await expect(page.locator('.ai-tetris-specials')).toHaveAttribute('open','')
  await expect(page.getByTestId('tetris-board')).toHaveAttribute('data-score','0')
})
